### ISSUE TITLE
Steel Tool Attack Speed is higher than expected (no cooldown)

### ISSUE THREAD

**Issue by OdieHerpaderp** [DM-Earth/Cabricality#58] opened 2022-10-09 12:16 UTC
The Industrial Revolution tools have a + to attack speed, which appears to make these weapons way faster than they should be. Given you can get these tools early, they're currently overpowered for their tier.

**Comment by JieningYu** [comment] 2022-10-09 12:34
dupe of https://github.com/DM-Earth/Cabricality/issues/56

**Closed as completed by JieningYu** 2022-10-09 12:34 UTC
